#!/usr/bin/env python3
"""
run_all_analyses.py — Run ALL 6 stocks through ALL 6 personas.

For each stock x persona, saves an individual markdown analysis with YAML
frontmatter, then creates a master consensus_matrix with all 36 results.
Uses ThreadPoolExecutor for parallel processing.
"""

import os
import sys
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

# Add hermes_home to sys.path for imports
HERMES_HOME = os.path.expanduser("~/hermes_home")
if HERMES_HOME not in sys.path:
    sys.path.insert(0, HERMES_HOME)

import persona_engine as pe

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

PERSONA_KEYS = ["oneil", "minervini", "qullamaggie", "lynch", "buffett", "david-ryan"]
PERSONA_LABELS = {
    "oneil": "O'Neil",
    "minervini": "Minervini",
    "qullamaggie": "Qullamaggie",
    "lynch": "Lynch",
    "buffett": "Buffett",
    "david-ryan": "David Ryan",
}

ALL_STOCKS = [
    pe.SN_DATA,
    pe.ETOR_DATA,
    pe.GFS_DATA,
    pe.INTR_DATA,
    pe.NRDS_DATA,
    pe.ZGN_DATA,
]

ANALYSES_DIR = os.path.join(HERMES_HOME, "analyses")
TODAY = datetime.now().strftime("%Y-%m-%d")


def analyze_one(persona_key: str, stock_data: dict):
    """Run a single persona analysis on a single stock."""
    analysis = pe.analyze_persona(persona_key, stock_data)
    return stock_data, persona_key, analysis


def save_individual(analysis: pe.PersonaAnalysis, stock_data: dict, persona_key: str):
    """Save one analysis as a markdown file with YAML frontmatter."""
    ticker = analysis.ticker
    ticker_dir = os.path.join(ANALYSES_DIR, ticker)
    os.makedirs(ticker_dir, exist_ok=True)

    # YAML frontmatter
    price = stock_data.get("price", "N/A")
    frontmatter = (
        "---\n"
        f"date: {analysis.date}\n"
        f"ticker: {ticker}\n"
        f"persona: {persona_key}\n"
        f"verdict: {analysis.verdict}\n"
        f"conviction: {analysis.conviction}\n"
        f"price: {price}\n"
        "---\n"
    )

    # Full analysis body — temporarily patch pe.sn_data so format_analysis
    # picks up the correct price for this stock
    orig_sn_data = pe.sn_data
    pe.sn_data = stock_data
    try:
        body = pe.format_analysis(analysis)
    finally:
        pe.sn_data = orig_sn_data

    filename = f"{persona_key}_{ticker}_{analysis.date}.md"
    filepath = os.path.join(ticker_dir, filename)
    with open(filepath, "w") as f:
        f.write(frontmatter)
        f.write(body)
    print(f"  Wrote: {filepath}")
    return filepath


def build_consensus_matrix(results: list):
    """Build the master consensus matrix from all results."""
    # results is list of (stock_data, persona_key, analysis)
    # Group by stock ticker
    rows = {}
    for stock_data, persona_key, analysis in results:
        ticker = stock_data["ticker"]
        if ticker not in rows:
            rows[ticker] = {}
        rows[ticker][persona_key] = analysis

    today = datetime.now().strftime("%Y-%m-%d")
    matrix_path = os.path.join(ANALYSES_DIR, f"{today}_consensus_matrix.md")

    lines = []
    lines.append(f"# Consensus Matrix — {today}\n")
    lines.append(
        f"All {len(ALL_STOCKS)} stocks × {len(PERSONA_KEYS)} personas = "
        f"{len(ALL_STOCKS) * len(PERSONA_KEYS)} analyses.\n"
    )
    lines.append(f"_Generated by Hermes Persona Engine v2 — Generative Agents architecture._\n")
    lines.append("")

    # --- Detailed results for each stock ---
    for stock_data in ALL_STOCKS:
        ticker = stock_data["ticker"]
        price = stock_data.get("price", "N/A")
        lines.append(f"## {ticker} — ${price}\n")
        lines.append(f"| Persona | Verdict | Conviction | Price Target / Notes |")
        lines.append(f"|---------|---------|------------|---------------------|")
        stock_rows = rows.get(ticker, {})
        for pk in PERSONA_KEYS:
            analysis = stock_rows.get(pk)
            if analysis:
                # Get first reasoning bullet for context
                first_bullet = ""
                if analysis.reasoning:
                    first_bullet = analysis.reasoning[0].get("analysis", "")[:80]
                lines.append(
                    f"| {PERSONA_LABELS[pk]} | **{analysis.verdict}** "
                    f"| {analysis.conviction:.1f} | {first_bullet} |"
                )
            else:
                lines.append(f"| {PERSONA_LABELS[pk]} | ERROR | — | — |")
        lines.append("")

    # --- Verdict summary table ---
    lines.append("## Summary Grid\n")
    lines.append(f"| Stock | Price | {' | '.join(PERSONA_LABELS[pk] for pk in PERSONA_KEYS)} |")
    header_mid = " | ".join("---" for _ in PERSONA_KEYS)
    lines.append(f"|------|-------|{header_mid}|")
    for stock_data in ALL_STOCKS:
        ticker = stock_data["ticker"]
        price = stock_data.get("price", "N/A")
        cells = []
        stock_rows = rows.get(ticker, {})
        for pk in PERSONA_KEYS:
            analysis = stock_rows.get(pk)
            if analysis:
                verdict = analysis.verdict
                conv = analysis.conviction
                # Color-code: BUY=🟢 HOLD=🟡 SELL=🔴 PASS=⚪ AVOID=⛔
                emoji = {"BUY": "🟢", "HOLD": "🟡", "SELL": "🔴", "PASS": "⚪", "AVOID": "⛔"}
                e = emoji.get(verdict, "❓")
                cells.append(f"{e} {verdict} ({conv:.1f})")
            else:
                cells.append("—")
        lines.append(f"| {ticker} | ${price} | {' | '.join(cells)} |")
    lines.append("")

    # --- Conviction heatmap ---
    lines.append("## Conviction Heatmap (average)\n")
    lines.append("| Persona | Avg Conviction |")
    lines.append("|---------|---------------|")
    for pk in PERSONA_KEYS:
        convs = []
        for stock_data in ALL_STOCKS:
            ticker = stock_data["ticker"]
            stock_rows = rows.get(ticker, {})
            analysis = stock_rows.get(pk)
            if analysis:
                convs.append(analysis.conviction)
        avg_conv = sum(convs) / len(convs) if convs else 0
        bar = "█" * int(avg_conv * 20)
        lines.append(f"| {PERSONA_LABELS[pk]} | {avg_conv:.2f} {bar} |")
    lines.append("")

    content = "\n".join(lines)
    with open(matrix_path, "w") as f:
        f.write(content)
    print(f"  Wrote: {matrix_path}")
    return matrix_path


def main():
    os.makedirs(ANALYSES_DIR, exist_ok=True)
    total = len(ALL_STOCKS) * len(PERSONA_KEYS)
    print(f"Running {total} analyses ({len(ALL_STOCKS)} stocks × {len(PERSONA_KEYS)} personas)...\n")

    results = []
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = []
        for stock_data in ALL_STOCKS:
            for pk in PERSONA_KEYS:
                futures.append(executor.submit(analyze_one, pk, stock_data))

        done = 0
        for future in as_completed(futures):
            done += 1
            stock_data, pk, analysis = future.result()
            results.append((stock_data, pk, analysis))
            sys.stdout.write(f"\r  Completed {done}/{total}: {PERSONA_LABELS[pk]} → {stock_data['ticker']}")
            sys.stdout.flush()

    print("\n\n=== Saving individual analyses ===")
    saved_files = []
    for stock_data, pk, analysis in results:
        fp = save_individual(analysis, stock_data, pk)
        saved_files.append(fp)

    print("\n=== Building consensus matrix ===")
    matrix_path = build_consensus_matrix(results)

    print(f"\n=== DONE ===")
    print(f"  {len(saved_files)} individual analysis files saved to {ANALYSES_DIR}/{{ticker}}/")
    print(f"  Consensus matrix: {matrix_path}")
    print(f"  Stock coverage: {', '.join(s['ticker'] for s in ALL_STOCKS)}")
    print(f"  Personas: {', '.join(PERSONA_LABELS[pk] for pk in PERSONA_KEYS)}")

    # Print a quick tally
    print("\n=== Quick verdict tally ===")
    verdicts = {}
    for _, _, a in results:
        verdicts[a.verdict] = verdicts.get(a.verdict, 0) + 1
    for v, c in sorted(verdicts.items(), key=lambda x: -x[1]):
        print(f"  {v}: {c}")
    print()


if __name__ == "__main__":
    main()
